name: push
on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.12
        uses: actions/setup-python@master
        with: { python-version: 3.12 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install cx_Freeze
        run: pip install cx_Freeze==7.0.0

      - name: Build installer
        working-directory: installer
        run: python setup.py build
      
      - name: Rename installer
        working-directory: installer/build
        run: mv exe.win-amd64-3.12 inf-notebook

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: installer/build/*
  
      - name: Install modules
        run: pip install -r requirements.txt
    
      - name: Build
        run: |
          python generate_service_account_info.py ${{ secrets.KEYINFO }}
          python generate_version.py ${{ github.ref_name }}
          python setup.py build
  
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: inf-notebook
          path: build/exe.win-amd64-3.12/*

  release:
    needs: [windows-build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Download exe
        uses: actions/download-artifact@v4
        with:
          name: inf-notebook
          path: build_inf-notebook

      - name: Zip
        working-directory: build_inf-notebook
        run: zip -r inf-notebook.zip ./*
  
      - name: Download installer
        uses: actions/download-artifact@v4
        with:
          name: installer
          path: build_installer
      
      - name: Move zip
        run: mv build_inf-notebook/inf-notebook.zip build_installer/inf-notebook/

      - name: Zip all
        working-directory: build_installer
        run: zip -r inf-notebook-${{ github.ref_name }}.zip ./inf-notebook

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build_installer/inf-notebook-${{ github.ref_name }}.zip
          asset_name: inf-notebook-${{ github.ref_name }}.zip
          asset_content_type: application/zip
