name: push
on:
  push:
    tags:
      - "v*"

jobs:
  windows-build-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.12
        uses: actions/setup-python@master
        with: { python-version: 3.12 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install modules
        working-directory: installer
        run: pip install -r installer_requirements.txt

      - name: Install cx_Freeze
        run: pip install cx_Freeze==7.0.0
    
      - name: Build
        working-directory: installer
        run: python installer_setup.py build
      
      - name: Rename
        working-directory: installer/build
        run: mv exe.win-amd64-3.12 inf-notebook-installer

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: installer/build/inf-notebook-installer

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.12
        uses: actions/setup-python@master
        with: { python-version: 3.12 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install modules
        run: pip install -r requirements.txt
    
      - name: Install cx_Freeze
        run: pip install cx_Freeze==7.0.0
    
      - name: Build
        run: |
          python generate_service_account_info.py ${{ secrets.KEYINFO }}
          python generate_version.py ${{ github.ref_name }}
          python setup.py build
  
      - name: Rename
        working-directory: build/
        run: mv exe.win-amd64-3.12 inf-notebook
  
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: inf-notebook
          path: build/inf-notebook

  release:
    needs: [windows-build, windows-build-installer]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: inf-notebook

      - name: Zip
        run: zip -r inf-notebook-${{ github.ref_name }}.zip inf-notebook
  
      - name: Download installer
        uses: actions/download-artifact@v4
        with:
          name: installer
      
      - name: Set environpment
        working-directory: installer
        run: |
          grep -E "version_installer(\s*)=" installer.py
          grep -E "version_installer(\s*)=" installer.py | awk -F'=' '{print $2}'
          grep -E "version_installer(\s*)=" installer.py | awk -F'=' '{print $2}' | sed 's/[ '\'']//g'
          echo "installer_version=$(grep -E "version_installer(\s*)=" installer.py | awk -F'=' '{print $2}' | sed 's/[ '\'']//g')" >> "$GITHUB_ENV"
      
      - name: Zip installer
        run: zip -r inf-notebook-installer-${{ env.installer_version }}.zip ./inf-notebook-installer

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./inf-notebook-${{ github.ref_name }}.zip
          asset_name: inf-notebook-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./inf-notebook-installer-${{ env.installer_version }}.zip
          asset_name: inf-notebook-installer-${{ env.installer_version }}.zip
          asset_content_type: application/zip
