name: push
on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.11
        uses: actions/setup-python@master
        with: { python-version: 3.11 }

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cx_Freeze==6.14.6

      - name: build
        run: |
          python generate_service_account_info.py ${{ secrets.KEYINFO }}
          python generate_version.py ${{ github.ref_name }}
          python setup.py build
  
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: inf-notebook
          path: build/exe.win-amd64-3.11/

  release:
    needs: [windows-build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Download Windows
        uses: actions/download-artifact@v1
        with:
          name: inf-notebook

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip
        run: |
          zip -r inf-notebook-${{ github.ref_name }}.zip ./inf-notebook

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./inf-notebook-${{ github.ref_name }}.zip
          asset_name: inf-notebook-${{ github.ref_name }}.zip
          asset_content_type: application/zip
